---
kind: pipeline
type: docker
name: container-images

platform:
  os: linux
  arch: amd64

steps:
  - name: shellcheck
    image: koalaman/shellcheck-alpine:latest
    commands:
      - shellcheck --shell sh --check-sourced --severity=info --exclude SC1091 --exclude SC2034 bin/*
    when:
      event:
        - pull_request
        - commit

  - name: build
    image: rancher/hardened-build-base:v1.17.5b7
    commands:
      - make all
    when:
      event:
        - tag
      instance:
        - drone-publish.rancher.io
  
  - name: docker-publish
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: "rancher/ecm-distro-tools"
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    volumes:
      - name: docker
        path: /var/run/docker.sock
    when:
      event:
        - tag
      instance:
        - drone-publish.rancher.io

  - name: failed-build-notification
    image: plugins/slack
    settings:
      template: "Build {{build.link}} failed.\n"
      channel: "TODO" # PR: Either create or choose the channel for these messages
      webhook:
        from_secret: slack_webhook # PR: This webhook is created upon request
    when:
      event:
        exclude:
          - pull_request
      instance:
        - drone-publish.rancher.io
      status:
        - failure

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock
